### ISSUE TITLE
exported module calls window, crashes in some enviorenments

### ISSUE THREAD

**Issue by goldylucks** [backtrace-labs/backtrace-js#8]
[this line ](https://github.com/backtrace-labs/backtrace-js/blob/master/lib/index.js#L8) is crashing when I import the package in the main electron process.

since the error crashing setup is so similar in the main and renderer process, I put them in the same util file in my project.

at the moment I need to mock the window object on the main process to avoid a crash.

Two easy possibilities to fix this:
```diff
// first option
- var crypto = window.crypto || window.msCrypto;
+ var crypto = window && window.crypto || window.msCrypto;

// second option
- var crypto = window.crypto || window.msCrypto;
- crypto.getRandomValues(uuidArray);
+ (window.crypto || window.msCrypto).getRandomValues(uuidArray);
```

If you want to strictly enable only importing this package in environments with `window` object (which I don't recommend), I suggest add this to the top of the file: 

```
if (typeof window === 'undefined') {
  throw new Error('backtrace-js should only be used in environments with the window object')
}
```

Thoughts?

**Comment by amadden80** [comment]
Thank you for filling the issue!  
We're looking into it and will follow up asap.

**Comment by amadden80** [comment]
Thank you again for bringing this up. Appreciate the feedback.

backtrace-js IS currently written for `window` based environments, i.e. a web-browser or electron-built-browser-window.  backtrace-js is expecting more than just `crypto` on the `window`.  It's also expecting constructors like `XMLHttpRequest` and methods like `addEventListener`.  It doesn’t seem to me your main process could really being using backtrace-js for this reason.  Even it it is importable with your modification.  

I'd currently recommend one or both of these paths:

1: See this electron integration guide which uses backtrace-js in rendering and crashReporter in main.  https://help.backtrace.io/integration-guides/application-frameworks/electron-integration-guide

2: Use backtrace-node for your main process and backtrace-js for your rendering process.  This would allow you to manually send reports.  If you want to use backtrace-node in electron, you'll have one obstacle.  Since `electron` already has an `uncaughtException` listener, you'll need to pass backtrace-node's initialize the option `allowMultipleUncaughtExceptionListeners: true` OR `disableGlobalHandler:true`.   I’d say go with `disableGlobalHandler`.  Now you can send your own reports with Backtrace.report.  

If both:   You could use crashReporter for uncaught errors (see article) and backtrace-node for sending caught errors via Backtrace.report.

Following your recommendation, I'm adding some validations for window to backtrace-js AND referencing window in initialize, therefore, your importing should work without the mocked window.  Regardless, the initialize should be called in the rendering process scope.

**Comment by goldylucks** [comment]
I know this package is for window based environments, that's why I said:

>since the error crashing setup is so similar in the main and rendererer process, I put them in the same util file in my project.

Thanks for the detailed answer :)

I read the article you recommended. Do you have a recommended way to start and stop enabling crash reports on the fly?

The electron crashReporter seem to only have a `start` method, and no `stop` or `kill` method.

Would also be great if we could pass a flag to `backtrace-js` on the fly to stop reporting. In our app we allow users to toggle error reporting from settings page.

I'm guessing this is a pretty common need for electron app developers.

**Comment by amadden80** [comment]
I am currently unaware of such `stop` ability.  
Very interesting thought there on backtrace-js!  I will bring this feedback into our discussions.

**Comment by mattmarcello** [comment]
@goldylucks do you feel as though this issue has been satisfactorily addressed?

**Comment by goldylucks** [comment]
@amadden80 calling `crashReporter.start` multiple times with `uploadServer` true/false works, so we can set that on the fly without needing for a restart.

I made a [PR](https://github.com/chentsulin/electron-react-boilerplate/pull/1616/files#diff-69ad5d99cee5ce42ddb9a1cf03d1024bR44) demonstrating that you can check out.

@mattmarcello I don't see any commit referencing this issue. Is this have been addressed?

**Comment by amadden80** [comment]
@goldylucks this comment introduced the error when there is not a window.   [Commit 1d53eaf4](https://github.com/backtrace-labs/backtrace-js/commit/1d53eaf49833e9e540167fa316ba827dfe3461dc)

Thank you for that info.
